### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by netoneko** [orbs-network/trash-panda#1]
Respond to standard SDK queries:
- [x] send tx
- [x] send tx async
- [x] run query
- [x] get tx status
- [ ] get tx status proof
- [ ] get block

Storage & relay:
- [x] store incoming transactions in the database
- [x] relay dropped transactions to the node and update their status in the local db
